MAJOR REDESIGN - BYO OpenAI Keys (#27)
* first attempt and comments

* Changes for BYO API keys feature and UI improvements

* Type fixes only

* Changes to address the feedbacks on the /gpt4 page

* Fixing compilation errorr

* Compilation error fix
496:15  Error: Missing "key" prop for element in iterator  react/jsx-key

* Transparent sticky navbar to blend with bg

* Small spi key text in same line

* Added top margin to 2nd line of api key message to keep it relaxed.

* Making components consistent

* FORMAT FIX, plus edit the text on 'please enter your OpenAI key' message

* move topBar into its own component, and improve the colors of the main chat messages

* fix background of text input box, scroll bar is better but styling is WIP

* huge number of fixes. The colors look good, the arrows are proper, the top bar is working, the scroll bars are nice

* Fixing transparent background of gpt4 model dropdown

* super minor copy improvement

* copy improvement to /materials

* Changes to fix gpt4 model settings background on gpt4 page

* spelling typo

* major redesign of course-wide key, addding Accordion ui

* placeholder trying to fix fetch keys

* VERY CONFUSED COMMIT ABOUT FETCHING KEYS ON CLIENT SIDE

* Revert "VERY CONFUSED COMMIT ABOUT FETCHING KEYS ON CLIENT SIDE"

This reverts commit 8d39866dbe20398e7a805f092b181ae39e74fbaa.

* Massive logic change for handling openai keys
1. Changes to encrypt and decrypt OpenAI key when setting course_metadata and when calling models api following the hierarchical logic: course_metadata_openai_key -> client open_ai_key
2. Handled the key on the open ai chat call following the hierarchical logic: course_metadata_openai_key -> client open_ai_key
3. Some Format fixes as well

* FULLY WORKING BYO OPENAI KEYS 🎉

* minor fix to remove axiom

* working, and removed vercel KV call in serverSideProps... next up, fully remove the function

* FULLY WORKING with NO getServerSideProps, so it's super fast omg

* beautiful message for users to enter OpenAI API key

* completed -- merging in main

* fix formatting on visibility tab.

* further improve formatting on visibility tab.

* adding nice accordian text to Visibility and admin access. very consistent

* copy improvement to Visibility text

* minor type fix

* minor copy improvement

* typo fix

* standardize text in upload logo box

* Bugfix to persist/use client side api key in/from local storage

* Notifications on course wide api key update

* Format fixes ONLY

* Changes to put focus on chatbar when introductory message is clicked and displaying api key sidebar button even when set in local storage

* working model select, but I'm trying to improve the handling of clicking away from the box

* Major refactor: FULLY WORKING model select and click-away. It's very
good

* FORMAT FIX ONLY

* FORMAT FIX ONLY

* remove settings button from sidebar

* logo sizing is decent, not incredible

* merged main into branch

* improved advanced model settings with standard drop down

* simplify 'Chat with documents' button text

* rebrand from UIUC Course AI to UIUC.chat

* much improved Logo css, nice dynamic expansion and contraction

* fix transparent background of model select dropdown

* Notification on chat completion api error

* Increasing timeout of notification so that people have time to read the error

* Font and color changes

* fully working example questions on /materials (just need to do /gpt4)

* FULLY WORKING example questions and intro message

* respect newlines in course intro message

* much improved logo on /gpt4. does proper sizing now.

* further improve logo format on small screens

* fix look and feel of Course Intro Message button

---------

Co-authored-by: rohanmarwaha <rohan13@illinois.edu>